//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRecruimentEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTUT
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public System.DateTime DayofBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string ApplyPosition { get; set; }
        public System.DateTime DateofApplication { get; set; }
        public string FileAttach { get; set; }
    }
}
